name: Update Log File

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update log file
        run: |
          echo "DATE $(date '+%Y-%m-%d %H:%M:%S')" >> LOG
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add LOG
          git commit -m "Update log file"
          git push
